# Generated by Django 4.1 on 2022-11-11 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_useritem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserItem',
            new_name='CartItem',
        ),
    ]
