# Generated by Django 4.1 on 2022-11-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_useritem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
