# Generated by Django 4.1 on 2022-11-14 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='purchased',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedItemIds', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=2, null=True)),
                ('totalPrice', models.CharField(blank=True, max_length=400, null=True)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('purchaseOwner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
