# Generated by Django 4.1.3 on 2022-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_cartitem_purchased_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='purchased',
            field=models.CharField(blank=True, default='False', max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
